### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by Lacyway** [project-fika/Fika-Plugin#11]
Retrieve data from server?

**Comment by DeadLeavez** [comment]
Im assuming you mean for the F12 interface. No other mods do localization as far as I know. But that shouldn't stop us if it's something we want. I don't thing grabbing from the server is a good idea though, seems necessarily complex and causes unnecessary network traffic. Could be stored in files next to the .dll. 

I think we should follow the practice of many other mods to have .dll in it's own folder inside of ``bepinex/plugins``. It might not do anything right now, but it would allow us to do things like add localization files, or any sort of files to the plugin project without changing file-tree structure in the future. And we've the perfect opportunity to do so now that we're also renaming and rebranding in the same swoop.

**Comment by Lacyway** [comment]
I don't think downloading the lang files would be too slow, it's already in the assets folder ready to go, we never finalized it. Sending raw data without generating it is fast. 

The point was to automatically detect the chosen language (so no F12 setting) and download the corresponding file and use those variables, this is what the server mod is ready for. Or we store it in the client and read from file as you said. 

@MerijnHendriks @TheSpartaPT what would be your preferred route?

**Comment by DeadLeavez** [comment]
If there are stuff in the server that need localization too, then it might be worth putting it there indeed.
