### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SaltZA** [project-fika/Fika-Plugin#119]
Getting an error message when trying to host and my friend's pc gets the same error msg. We're using the most recent spt (3.9.4) and recent Fika. Heres the error message:

[UNHANDLED][/fika/raid/dedicated/getstatus]

Any ideas?

**Comment by ArchangelWTF** [comment]
Tell him to update his Fika-server.

**Comment by Lacyway** [comment]
This is not a bug, your server mod is not installed correctly.
