### ISSUE TITLE
possibility to mass send items via the select ability

### ISSUE THREAD

**Issue by xThomate** [project-fika/Fika-Plugin#120]
It is kind of annoying, having to send every single item seperately.

the select ability is a feature of this mod
|
--> https://hub.sp-tarkov.com/files/file/1860-ui-fixes/

**Comment by Lacyway** [comment]
You can put everything in a container/backpack for now.
I will look into improving this in the future (e.g. using the crafting UI where you can select items), but for now it will be a low prio as we have core issues still being worked on.

Mind posting this on the discord as a feature request? We use that to track all requests. Thanks!
