### ISSUE TITLE
[BUG] am I doing something wrong?

### ISSUE THREAD

**Issue by LeooM99** [project-fika/Fika-Plugin#132]
I followed the entire installation guide step by step. Using the radmin vpn program. And the game does not go beyond the loading screen, in addition, when you press F12 nothing comes out to force the IP connection, etc.  

using version 3.9.0 aki mod, also clarify i downloaded and used the appropriate version of the fika mod for said version of aki.

![error fika project](https://github.com/user-attachments/assets/df46f5a3-525c-437b-90f6-c59ca8f51000)

**Comment by Lacyway** [comment]
You are doing something wrong. Issues are for bugs only, for support go to our Discord.
