### ISSUE TITLE
[BUG] Not cached bundles not loading from server

### ISSUE THREAD

**Issue by hellchickens** [project-fika/Fika-Plugin#140]
**Describe the bug**
Just updated to current latest SPT (3.9.6) and FIKA server /plugin, added few new mods, but noticed that client stuck on bundle download from server. Due to server log bundle never gets requested, so client init is doomed. Removed new mods - things went smooth with already cached stuff. If I clear cache - same behavior. Same stuff w/wo dedicated plugin.

**To Reproduce**
1. Add new (never cached) server mod that have bundles or any other downloadable content for client (tried with several, on screenshot is that one https://hub.sp-tarkov.com/files/file/2148-toxic-glock-bros/#overview)
2. Launch client

**Expected behavior**
Server mods downloaded and cached, client loads to main menu.

**Screenshots**
![image](https://github.com/user-attachments/assets/401de71e-f406-481c-9da2-93098aafdcee)

**Log files**
[Player.log](https://github.com/user-attachments/files/16649000/Player.log)

**Desktop (please complete the following information):**
 - Fika server 2.2.8
 - Fika plugin 0.9.8995.14684

**Comment by ArchangelWTF** [comment]
It's a SPT issue: https://dev.sp-tarkov.com/SPT/Modules/pulls/160

**Comment by hellchickens** [comment]
> It's a SPT issue: https://dev.sp-tarkov.com/SPT/Modules/pulls/160

Freaking fast reply! Thanks, will wait new spt patch tho

**Comment by ArchangelWTF** [comment]
Fixed in the latest SPT release.
