### ISSUE TITLE
[BUG] Random mag unload cancellation 

### ISSUE THREAD

**Issue by hellchickens** [project-fika/Fika-Plugin#141]
**Describe the bug**
Sometimes mag unload stops after first bullet out. Mostly faced with mag_pm_izhmeh_9x18pm_8

**To Reproduce**
1. Bug is random, just unload mags in raid

**Expected behavior**
Full unload of mag to 0 rounds.

**Screenshots**
n/a

**Log files**
```
[Error  : Fika.Core] 666c71810002026259bfe4aa - Client operation rejected by server: 4967 - OperationType: GClass2880, Owner: 666c71810002026259bfe4aa, 
InternalOperation: OperationType: SplitOperationClass, Owner: 666c71810002026259bfe4aa, 
From: patron_9x18pm_RG028_gzh 573720e02459776143012541, Address: stackslot cartridges in item mag_pm_izhmeh_9x18pm_8 (id: 64c23df38c55c412dc222f05), ID: 66c20dc9fa2f0e9f8300000a, Stack: 3, 
To: grid 1 in item wartech_mk3 (id: afd0fe81e72850d2728bfe49) at (x: 0, y: 0, r: Horizontal), 
Count: 1, 
NewId: 66c208394462b8bbe20001ec
Reason: 
NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Rigidbody.get_velocity_Injected(UnityEngine.Rigidbody,UnityEngine.Vector3&)
  at UnityEngine.Rigidbody.get_velocity () [0x00000] in <10a2290b9f3045c2a90083d2063fb646>:0 
  at SAIN.SAINComponent.Classes.WeaponFunction.GrenadeVelocityTracker.Update () [0x0001e] in <6a7ce42854e447f0ba052e70c80ede2a>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class362:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
 
```

[Player.log](https://github.com/user-attachments/files/16650082/Player.log)

**Desktop (please complete the following information):**
 - SPT 3.9.6
 - Fika server 2.2.8
 - Fika plugin 0.9.8995.14684
 - Fika dedicated plugin 1.0.4
 Server and dedicated client are running on one laptop, game client on another pc, all in same local network. All client plugins configs and mods are same on both machines.

**Additional context**

**Comment by Lacyway** [comment]
This is most likely linked to the explanation in your other issue as it causes a world state desync: https://github.com/project-fika/Fika-Plugin/issues/142#issuecomment-2295327023

**Comment by hellchickens** [comment]
Tried, haven't met in raid, suppose resolved.

**Comment by Lacyway** [comment]
I've asked DOKDOR to update our FAQ
