### ISSUE TITLE
[BUG] Ammo packages spawn no ammo on unpacking

### ISSUE THREAD

**Issue by hellchickens** [project-fika/Fika-Plugin#142]
**Describe the bug**
All ammo packages picked from the ground loot don't spawn any ammo on unpacking. Packages from any other sources work as expected.

**To Reproduce**
1. Find any ammo package (any size, any cal) on ground loot
2. Loot it in inventory
3. Unpack it

**Expected behavior**
Ammo package disappeared and valid number of ammo is spawned in inventory.

**Screenshots**
n/a

**Log files**
[Player.log](https://github.com/user-attachments/files/16650082/Player.log)

**Desktop (please complete the following information):**
    SPT 3.9.6
    Fika server 2.2.8
    Fika plugin 0.9.8995.14684
    Fika dedicated plugin 1.0.4 
    Server and dedicated client are running on one laptop, game client on another pc, all in same local network. All client plugins configs and mods are same on both machines.

**Additional context**
Not sure if it Fika or SPT bug.

First noticed when unloaded 120 ammo box right on the ground (I'm using https://hub.sp-tarkov.com/files/file/1870-loot-radius/#overview) and got nothing. Then tried to move ammo box in inventory (all possible containers) and in raid containers, result was the same - just deleted ammo box.

**Comment by ArchangelWTF** [comment]
Can confirm this issue does exist, encountered it as well this weekend when cooping with someone that had the same exact thing.. Throws a nullref in onitempacket received for the host

**Comment by hellchickens** [comment]
I believe I'm not using any mod that modify anything around that mechanic. The only thing that is modified about ammo - stack size - it's enlarged to 1k rounds per stack

**Comment by Lacyway** [comment]
You are using UIFixes which causes this error.
`Loaded plugin: [Tyfon.UIFixes] with GUID [Tyfon.UIFixes] and crc32 [3824078781]`

Disable the ammo put in same place function in the advanced settings and see if you ever experience it again. This was discussed a few weeks ago with Tyrion so he added the option to disable it for Fika compatibility.

@ArchangelWTF are you running UIFixes?

**Comment by ArchangelWTF** [comment]
> @ArchangelWTF are you running UIFixes?

Yeah, we are running UI fixes although I have most of the things disabled from it so it could very well be that the people I play with do not.. Will check

**Comment by Lacyway** [comment]
> > @ArchangelWTF are you running UIFixes?
> 
> Yeah, we are running UI fixes although I have most of the things disabled from it so it could very well be that the people I play with do not.. Will check

It's an advanced setting, so I'm willing to bet that you (or at least your friends) have not disabled it.

**Comment by hellchickens** [comment]
> > > @ArchangelWTF are you running UIFixes?
> > 
> > 
> > Yeah, we are running UI fixes although I have most of the things disabled from it so it could very well be that the people I play with do not.. Will check
> 
> It's an advanced setting, so I'm willing to bet that you (or at least your friends) have not disabled it.

I suppose such things have to be in FAQ in Docs repo to avoid same things go rounds. Thx, will check how it works.
Also have different question about SAIN configs: does it apply from dedicated client machine? As I noticed that bot configs were working when one pc was server and client same time, but things went default when I've launched from dedicated client on different pc

**Comment by Lacyway** [comment]
> > > > @ArchangelWTF are you running UIFixes?
> > > 
> > > 
> > > Yeah, we are running UI fixes although I have most of the things disabled from it so it could very well be that the people I play with do not.. Will check
> > 
> > 
> > It's an advanced setting, so I'm willing to bet that you (or at least your friends) have not disabled it.
> 
> I suppose such things have to be in FAQ in Docs repo to avoid same things go rounds. Thx, will check how it works. Also have different question about SAIN configs: does it apply from dedicated client machine? As I noticed that bot configs were working when one pc was server and client same time, but things went default when I've launched from dedicated client on different pc

It uses the settings of the local client, so if you are using a dedicated client it will use the settings in its SAIN folder. I set it up on my own client and then move it over to the dedicated.

**Comment by hellchickens** [comment]
> > @ArchangelWTF are you running UIFixes?
> 
> Yeah, we are running UI fixes although I have most of the things disabled from it so it could very well be that the people I play with do not.. Will check

![image](https://github.com/user-attachments/assets/74f10885-f93e-4d37-9084-32eef1c79b2e)

**Comment by hellchickens** [comment]
Works as expected., ty

**Comment by hellchickens** [comment]
> I thought I fixed this for fika :( @hellchickens did this repro _only_ for ammo boxes you found on the ground? And was it all sizes or only the 120 ones?

Only from ground loot, from cases/bodies was ok. All sizes, no matter of cal and amount.

**Comment by tyfon7** [comment]
I'd like to fix it, but yeah I can make it default off if fika detected, at least for the short term.

**Comment by Lacyway** [comment]
> I'd like to fix it, but yeah I can make it default off if fika detected, at least for the short term.

Let me know if I can help.
