### ISSUE TITLE
[ENHANCEMENT] Extend spawn control options

### ISSUE THREAD

**Issue by hellchickens** [project-fika/Fika-Plugin#143]
**Is your feature request related to a problem? Please describe.**

As fika-plugin config is used by dedicated-client plugin I'd like to see more extended bot spawn config. Current approach to spawn exactly the same moment as bot is killed is kinda broken, as bot can be spawned right on ur face or 5 meters behind you. The most fun part to nade N bots same time and receive them few meters away by respawn. Often i see spawn of "enemies" on the very same spot: few PMC and SCAVs got spawned same place 2-3 meters away from each other and starting meat grinder in 5 sec. For example Very often near fortress and crack house on customs. 8 mins on raid i found 17 dead bodies on 2nd floor of crack house. Too intense.

**Describe the solution you'd like**
Ability to control more spawn options:

- min spawn distance to player
- min/max bot respawn timer - to make it more like DONUTS spawn waves, but without changing spawn points 
- spawn ratio: bear/usec
- min spawn distance to "enemy" bot
- bot squad spawn control (amount, chance): for example bot squads of 4 pmc with 10% chance if there are 4 spawn slots for the moment
- boss spawn chance

**Describe alternatives you've considered**

There are mods that already do that things, but for unknown for me reasons them all don't have all the logic in single mod in convenient way and overlapping few mods with same logic leads to lot of bugs and weird behavior. 

**Additional context**
Also I highly recommend to disable by default despawn option, as it leads to issues in extended (1h+) raids or if using "dynamic maps" mod as on despawn action client have no idea that it has to clear coordinates for despawned bot and it's dungling, making map unusable in 10-15 minutes. Also in my tests I've noticed very high fps impact on every connected client

**Comment by Lacyway** [comment]
Most of our spawn options are dated when performance was a bigger problem. Most mods now solve those problems, or most people run the dedicated client. I personally have left the AI control behind and no longer actively work on it. I am going to say out of scope, but I will leave this for any other contributor to take a look at or if I decide to in the future.

>Also I highly recommend to disable by default despawn option, as it leads to issues in extended (1h+) raids or if using "dynamic maps" mod as on despawn action client have no idea that it has to clear coordinates for despawned bot and it's dungling, making map unusable in 10-15 minutes. Also in my tests I've noticed very high fps impact on every connected client

Every client is aware of a disposed bot, it is sent from the server to all clients. This sounds more like a problem with the map mod not handling disposed bots correctly rather than Fika.

We're nearing 3.10 and have lots of stuff coming up in our backlog.

**Comment by DeadLeavez** [comment]
Fika doesn't provide anything that spawns any enemies. only ways to prevent and despawn them. It's always been other mods (or regular spt) that does the spawning. I don't think fika should ever have spawning options, that can be left to other mods.
