### ISSUE TITLE
[BUG] [3.10] Send item doesn't appear in inventory

### ISSUE THREAD

**Issue by ArchangelWTF** [project-fika/Fika-Plugin#144]
Probably needs to be re-done due to BSG updating their context menu in 0.15

**Comment by Lacyway** [comment]
![image](https://github.com/user-attachments/assets/c45b9e06-220e-4631-957b-8d2a374c5de1)
Appears for me, what do you mean?

**Comment by ArchangelWTF** [comment]
Incorrect data in the initialization of the plugin due to SPT still having incorrect data was not getting this to load correctly, works perfectly fine commenting that out.
