### ISSUE TITLE
[BUG/3.10] Client fails at auto connecting to Dedicated

### ISSUE THREAD

**Issue by ArchangelWTF** [project-fika/Fika-Plugin#158]
When setting up a raid with a dedicated client, the person who sets up the raid fails to auto-join with the following logs happening immediately in the console

```[Info   :NetManagerUtils] FikaGameObject has been created!
[Info   :NetManagerUtils] FikaPingingClient has started!
[Info   : Fika.Core] Attempting to connect to host session...
[Info   :NetManagerUtils] Destroyed FikaPingingClient

**Comment by Lacyway** [comment]
Fixed with https://github.com/project-fika/Fika-Plugin/commit/f5f09f499b132ac09a60aaadd065161d7babea84
