### ISSUE TITLE
[ENHANCEMENT] Quality of Life Changes to HUD/Menu

### ISSUE THREAD

**Issue by Hazeofdream** [project-fika/Fika-Plugin#188]
Allow an Option to remove the FIKA Print on one's hud, I get It's to distinguish it from Live, but it should atleast have an option to disable during raids, Many may not consider this a big deal but I know alot of people that want 100% control over what is printed on their hud, no matter how minor, whether for preference or to adhere to a HUD style for a mod.
![image](https://github.com/user-attachments/assets/95e0e041-cb30-4537-ab66-a81ca614939b)

Additionally, allow the removal of the main menu's FIKA message, I get that It's to inform of scam versions of FIKA, but It gets annoying after the 4000th launch, and even more annoying if you are debugging your game or changing settings that require a relaunch, as this causes more popups and steps to deal with.

This one in particular would be better as a separate button on the menu then a full-on popup that you need to close.
![image](https://github.com/user-attachments/assets/a265760a-40f5-427c-9d21-28cd4c23b838)

**Comment by trippyone** [comment]
No. But thanks for your feedback

**Comment by Lacyway** [comment]
First is already possible if you enable advanced settings in the configuration manager. 

Second won't happen due to past incidents.
