### ISSUE TITLE
[FEATURE] UDP Holepunch

### ISSUE THREAD

**Issue by maxomatic458** [project-fika/Fika-Plugin#21]
Add UDP holepunching so port forwarding is not required (for most types of NATs)

This can either be implemented fully P2P
* all players would need to share their public IPs with eachother

Or with a central roundevouz server
* that would exchange their IPs (could maybe be implemented via the friends list)

**Comment by Lacyway** [comment]
This is something that @trippyone will add, he already has the code for it ready.
