### ISSUE TITLE
[BUG] Joining server hangs while attempting to load main menu

### ISSUE THREAD

**Issue by TheInfamousAlk** [project-fika/Fika-Plugin#246]
I am not entirely sure if this is server or client related.

So I have SPT+fika set up in my Unraid server via Docker. The server starts okay, the launcher connects to the server just fine and loads my profile, and when I try to launch the game, it loads until it tries to load the main menu, at which point I get this in the server logs and my game just sits at the blank forest background forever:

```
[Client Request] <IP REDACTED> \client\menu\locale\en
Error: unexpected end of file
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
Error: unexpected end of file
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
```

I have narrowed it down to some sort of network issue, but I can't figure out what. When I connect to my server machine via my local network address, it works. When I enter in my domain name (which just goes through cloudflare to my home's public IP address, then through my SWAG container via https, SWAG routes anything from tarkov.my.domain to the correct port, which is how it connects at all), it fails as described above.

I found that in my nginx (swag) logs, it is throwing an error 499, which I think means the client cancelled the request before it was completed, which doesn't make sense if it works when I specify my local address. From nginx:

`192.168.1.1 - - [18/Dec/2024:21:51:02 -0500] "POST /client/menu/locale/en HTTP/1.1" 499 0 "-" "UnityPlayer/2019.4.39f1 (UnityWebRequest/1.0, libcurl/7.80.0-DEV)"`

I also found this in the backend.log file on my client: (it is the only thing in that file, and also appears in the traces log)
`2024-12-18 21:50:59.103 -05:00|0.15.5.1.33420|Info|backend|---> Request HTTPS, id [1]: URL: http://TARKOV.MY.DOMAIN/client/menu/locale/en, crc: .  `

I can't tell what this means. I think this is the next piece of the puzzle, but I don't know where to go from here.

**Comment by robpneu** [comment]
Not a fika issue. EFT client itself does not support HTTPS. See my diagnostics here: https://discord.com/channels/1202292159366037545/1254935152103264296

**Comment by TheInfamousAlk** [comment]
That makes sense. Though through SWAG, SPT can't actually tell people are using https to get to it, since it still serves everything via http which is then repackaged as https later on by swag/nginx. It may also have to do with the websocket (ws://0.0.0.0:6969 as opposed to https://0.0.0.0:6969) which could also be broken in the same way by your method of forcing https. 

Either way, I have resigned to just bypassing swag and port forwarding 6969 through my router directly.
