### ISSUE TITLE
[BUG]Can't select amount of players

### ISSUE THREAD

**Issue by zhua-w** [project-fika/Fika-Plugin#253]
It happens in PMC and SCAV mode

**To Reproduce**
Simply go to the server browser page

**Expected behavior**
Can see the player amount setting of course

**Screenshots**
![image](https://github.com/user-attachments/assets/549b40c2-2f07-453c-8829-fe8735b6b650)

**Log files**
Please attach your `Player.log` from `%Appdata%\..\LocalLow\Battlestate Games\EscapeFromTarkov`
Attached!
[Player.log](https://github.com/user-attachments/files/18226125/Player.log)
[LogOutput.log](https://github.com/user-attachments/files/18226130/LogOutput.log)

**Desktop (please complete the following information):**
 - SPT 3.10.3 Fika Version [1.1.0.0] Server [2.3.4]

**Comment by raphaelstuart** [comment]
If you have the latest version of fika. This is a feature not a bug i think.
Change log for Fika Core v1.1.0.0 said:
```
Major Change: The game start has received a major overhaul. You now start the game as before, but without selecting X players to play with. The host (or the one requesting the dedicated session) will receive a new button labeled "Start Raid" after loading the map that will start the raid and block any new users from joining.
```

**Comment by Lacyway** [comment]
This is a feature, not a bug.

**Comment by zhua-w** [comment]
Ahh I see
Sorry for the wrong issue

**Comment by zhua-w** [comment]
But I think it's better to change this to some thing like "Dedicated host option"
![image](https://github.com/user-attachments/assets/214b5639-6408-438f-b3fe-16fad2f06f51)

**Comment by Lacyway** [comment]
Will do
