### ISSUE TITLE
[WIP FEATURE] Rejoining

### ISSUE THREAD

**Issue by CWXDEV** [project-fika/Fika-Plugin#28]
Goal: 
To be able to rejoin at the same location of DC, along with everything being synced up

Tasks:
- [x] When disconnecting, change that players spawnpoint to match DC'd position.
- - [x] Position
- - [x] Rotation
- - [x] Prone
- - [x] Pose
- - [x] Fix Dead players reconnecting being able to "spawn" again (host has a new player object) - (shots and looting is synced)
- - [x] Sync HP and injuries
- - - [x] Fix injuries not being synced
- - - [x] Fix some injuries being duplicated
- - - [x] Fix Blacked limbs not being blacked on reconnect
- - [x] Sync Quests and achievements
- [x] Fix Exfils not working for clients after reconnect
- [x] Fix Time not syncing back up
- [x] Sync map doors.
- [x] Sync map windows.
- [x] Sync map lights.
- [x] Sync smokes.
- - [x] Fix Error with bundles not being loaded
- - [x] Fix no smoke being created (might be a BSG issue)
- [x] Sync Bot Deaths.
- [x] Sync map loot.
- [x] Sync inventories.
- - [x] Fix guns starting with overheat on reconnect
- - [x] Fix Error with bundles not being loaded and softlocking client
- [x] Sync Airdrops
- - [x] Fix Box being slight out of sync 
- [x] Sync BTR
- [x] Add option to rejoin on menu.
- [x] Add Retry connecting
- [x] Update to 3.9 branch
- - [x] Fix Position (goes back to og spawnpoint)
- - [x] Fix InventoryPacket Errors
- - [x] Investigate `IncreaseLoadedPlayers: could not find netId 2!` error for host
- - [x] investigate `No LootItem component for item *item name* (id: *item id*)` - backpack (assume this is any container that is on the player) - Client
- - [x] Fix Packets throwing nulls when client recieves them too early
- [x] CoopClientQuestController changed type signiture, need to check this works

**Comment by CWXDEV** [comment]
Changes between 21fb42f and d597014 caused `2024-05-18 18:00:32.137 +01:00|0.14.1.2.29197|Error|Default|Coroutine couldn't be started because the the game object 'TimerPanel' is inactive!` error, will come back to this.
before this basically everything was done, now existing Bots and Players dont spawn for reconnecting player

**Comment by Lacyway** [comment]
> Changes between [21fb42f](https://github.com/project-fika/Fika-Plugin/commit/21fb42f2589fb742ffc8db9088b6501db7019da5) and [d598014](https://github.com/project-fika/Fika-Plugin/commit/d59801427d238b736a582dc3a58b6b4edc1c8c45) caused `2024-05-18 18:00:32.137 +01:00|0.14.1.2.29197|Error|Default|Coroutine couldn't be started because the the game object 'TimerPanel' is inactive!` error, will come back to this. before this basically everything was done, now existing Bots and Players dont spawn for reconnecting player

At what stage does this occur?

**Comment by CWXDEV** [comment]
https://github.com/project-fika/Fika-Plugin/pull/39/commits/5ccd9c6e2edf41b764f08665764c27343e8082b3 fixed my issue with this, might stop others getting "waiting for players" also

**Comment by CWXDEV** [comment]
- [ ] check changes for shared quest tracking has had no effect to reconnecting quest changes
- [ ] check changes for latest client
- [ ] conform to contributing.md
