### ISSUE TITLE
Last bullet stuck in mag when unloading in container

### ISSUE THREAD

**Issue by MerijnHendriks** [project-fika/Fika-Plugin#32]
## How to replicate

1. Grab a magazine attached to an AK that you hold in your hands
2. Move the magazine into an external container (corpse, air drop, etc)
3. Unload the magazine
4. The last bullet will show "Cannot unload bullet, in use" and magazine is stuck at 1/x

**Comment by ekuland** [comment]
This occurs in the live game.
