### ISSUE TITLE
Raid for location not properly cleared upon session end

### ISSUE THREAD

**Issue by MerijnHendriks** [project-fika/Fika-Plugin#33]
After the raid is over, select the same, character, location and time.
The old raid is still there after completing it.
The same happens when closing the match before another player joined.
You can still create a new raid and have other players connect to it on the same settings.

![image](https://github.com/project-fika/Fika-Plugin/assets/54717671/b6e5199d-5fee-4c58-b56f-93be2bad990a)

**Comment by Lacyway** [comment]
This is handled on the server.
