### ISSUE TITLE
Host offloading - temporary workaround

### ISSUE THREAD

**Issue by IAMBUDE** [project-fika/Fika-Plugin#41]
I'd like to pitch an idea regarding raid offloading.

As you may know, some people fortunate enough to have another decent PC around, can use that PC to host a raid, offloading the AI work onto that machine.
This increases the performance for the 'original would be host' by a lot and also increases the potential AI amount ceiling.

Currently, starting a raid on that machine means moving to the PC (or using RDP) and requires multiple different clicks, such as choosing the map, raid time and skipping the low hp screen.
It's certainly not that much of a hassle but a direct integration would also allow people without access to the host PC to start raids, eliminating the need to provide VPNs to friends, so they can start the desired raid without me.

Would it be possible, as a temporary workaround until (if ever) headless servers are available, to use Fika to control the 'host player', making it start a desired raid with the desired amount of players?

Additional features could be
- Don't spawn the host player in the raid (or simply kill it automatically), removing the need to manually kill the player
- Automatically end the raid when every connected client disconnected (not using the instant disconnect functions so people can still spectate), meaning that he host will exit the raid if its the only person left automatically
- Automatically exit the game after a raid or a configurable amount of raids, using an automation script to restart it afterwards (to combat potential accumulative performance issues)
- Skipping the post raid report, placing the host back into the main menu, ready for another raid

I think a good way would be to integrate it into the HOST RAID screen, here's a very rough example on how this could look like:
![Screenshot_20240513_043042](https://github.com/project-fika/Fika-Plugin/assets/93278696/85d6b7c4-aecd-40e0-a56a-902fc3e89d0a)

The performance difference is incredible and warrants a deeper look at this. Left is my normal client, right is my host. Normally I'd run lighthouse with 40-60 FPS, now its between 80-120.
![Screenshot_20240512_154300](https://github.com/project-fika/Fika-Plugin/assets/93278696/8baa38e2-19ea-4966-93ec-feb72595ce12)

**Comment by trippyone** [comment]
This is something that is being worked on by me. The first goal is to provide a web interface to manage a Tarkov instance and host raids. The final goal is to run the Tarkov instance without graphics/reduced resource usage.

**Comment by maxomatic458** [comment]
@trippyone is there a public repo for that yet?

also will this be a fully custom server, or will it be a modded non-graphic version of the tarkov client?

also thanks for working on that, im really excited for that!

**Comment by BulldogMafia** [comment]
> I'd like to pitch an idea regarding raid offloading.
> 
> As you may know, some people fortunate enough to have another decent PC around, can use that PC to host a raid, offloading the AI work onto that machine. This increases the performance for the 'original would be host' by a lot and also increases the potential AI amount ceiling.
> 
> Currently, starting a raid on that machine means moving to the PC (or using RDP) and requires multiple different clicks, such as choosing the map, raid time and skipping the low hp screen. It's certainly not that much of a hassle but a direct integration would also allow people without access to the host PC to start raids, eliminating the need to provide VPNs to friends, so they can start the desired raid without me.
> 
> Would it be possible, as a temporary workaround until (if ever) headless servers are available, to use Fika to control the 'host player', making it start a desired raid with the desired amount of players?
> 
> Additional features could be
> 
> * Don't spawn the host player in the raid (or simply kill it automatically), removing the need to manually kill the player
> * Automatically end the raid when every connected client disconnected (not using the instant disconnect functions so people can still spectate), meaning that he host will exit the raid if its the only person left automatically
> * Automatically exit the game after a raid or a configurable amount of raids, using an automation script to restart it afterwards (to combat potential accumulative performance issues)
> * Skipping the post raid report, placing the host back into the main menu, ready for another raid
> 
> I think a good way would be to integrate it into the HOST RAID screen, here's a very rough example on how this could look like: ![Screenshot_20240513_043042](https://private-user-images.githubusercontent.com/93278696/329905106-85d6b7c4-aecd-40e0-a56a-902fc3e89d0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NjkzMDYsIm5iZiI6MTcxOTY2OTAwNiwicGF0aCI6Ii85MzI3ODY5Ni8zMjk5MDUxMDYtODVkNmI3YzQtYWVjZC00MGUwLWE1NmEtOTAyZmMzZTg5ZDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDEzNTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MTVlMWQ2OTNiZjY5ODYwODY0YmYyNjliNTYwZDNlYmJmNGU0MTQ3Yjk3Yjc5NjE4NmFhODUwMWZkOTY0Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.40jAEtyVWLZG4XpD5NU_crKSty113JwAeqAtLjxzt2Y)
> 
> The performance difference is incredible and warrants a deeper look at this. Left is my normal client, right is my host. Normally I'd run lighthouse with 40-60 FPS, now its between 80-120. ![Screenshot_20240512_154300](https://private-user-images.githubusercontent.com/93278696/329854256-8baa38e2-19ea-4966-93ec-feb72595ce12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NjkzMDYsIm5iZiI6MTcxOTY2OTAwNiwicGF0aCI6Ii85MzI3ODY5Ni8zMjk4NTQyNTYtOGJhYTM4ZTItMTllYS00OTY2LTkzZWMtZmViNzI1OTVjZTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDEzNTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMGI4MGIxMGViY2M2N2YzZDEyZThjNjMwMTg5ZjgyYjZmZjZkMjA3ODViMjc1ZDUwODQxYmQ5YjQ2NDk4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GiLkWemaplrwlIpDihkLFrhOsx2XQcea4L7kcYaycLw)

had a question about starting the raid as host without spawning, how do you accomplish this instead of having to kill the host everytime?

**Comment by maxomatic458** [comment]
@BulldogMafia thats not possible at the moment, it would have to be added in the plugins code. But it is being worked on here https://github.com/nexus4880/Fika-Plugin/tree/headless-client and https://github.com/nexus4880/Fika-Server/tree/3.9.0
