### ISSUE TITLE
[BUG] bepinex plugin version does not match fika release version

### ISSUE THREAD

**Issue by maxomatic458** [project-fika/Fika-Plugin#42]
https://github.com/project-fika/Fika-Plugin/blob/c8a08435dd7f8e4989c6c190b000664da218853e/Fika.Core/FikaPlugin.cs#L40

that should probably be changed to ``0.9.8892.36315``

**Comment by Lacyway** [comment]
The version number is generated at compile time, so we cannot modify this after. I might change the numbers later but for now I'll treat this as a non-issue.

**Comment by maxomatic458** [comment]
i guess it might be better to just "make up" version numbers instead on relying on the generated ones

**Comment by Lacyway** [comment]
> i guess it might be better to just "make up" version numbers instead on relying on the generated ones

Yep, I'll do something like this down the line.
