### ISSUE TITLE
Bosses don't spawning

### ISSUE THREAD

**Issue by ScarletRedMan** [project-fika/Fika-Plugin#46]
I set a 100% chance for all bosses to spawn and they just won't spawn. I installed a mod that detects spawn bosses (BossNotifier). The plugin sends a notification, but there are no bosses. Without Fika, all bosses spawn normally.

Installed mods: AmandsGraphics, SAIN (BigBrain + Waypoints), LootingBots, QuestingBots, BossNotifier, Fika

**Comment by Lacyway** [comment]
Use our discord for issues and follow the guidelines in there,.
Regarding your issue, try without Looting and Questing bots. I use SVM to modify the spawns and I am consistently getting bosses at 100% on my dev client. BossNotifier is also known not to work that well with Fika, so I wouldn't use it as a reliable source to determine whether they spawned or not.
