### ISSUE TITLE
Equipment presets have dogtags in them

### ISSUE THREAD

**Issue by CWXDEV** [project-fika/Fika-Plugin#53]
On creating a CoopBot a dogtag is added at Start, assuming that person completes the raid (have not tried on death), their profile now contains a Dogtag, this breaks the equipment presets.

steps to reproduce:
1. make profile,
2. go in game,
3. make a preset with what you have,
4. go in raid and survive,
5. go to preset and apply loadout,
6. new dogtag in stash ?? Profit

you can also survive a raid and save a preset, if that dogtag gets removed via another preset, the first preset cannot be applied.

unsure how you'd want to handle that, my opinion would have the client process adding a dogtag on death

**Comment by Lacyway** [comment]
Handling the dog tag on death is not possible due to the structure of the current implementations.
Are you saying you are returning with _your own dog tag_?

**Comment by CWXDEV** [comment]
aighty, but yes seems so
