### ISSUE TITLE
[ENHANCEMENT] Ability to change the max packet size

### ISSUE THREAD

**Issue by maxomatic458** [project-fika/Fika-Plugin#64]
**Is your feature request related to a problem? Please describe.**
If your network/vpn does not support IP fragmentation, packet loss can occur

**Describe the solution you'd like**
Either lower the default packet size, or let the user choose it from within the plugins menu

**Describe alternatives you've considered**
Dont add it as its a pretty uncommon edge case

**Additional context**
i was trying to use https://playit.gg/ (a reverse proxy that only needs to be installed on the host side) with Fika, but since they dont support IP fragmentation packets got lost. Building the Plugin from source with a lower packet size fixed that problem

**Comment by Lacyway** [comment]
Could you tell me exactly which option you want changed?

**Comment by maxomatic458** [comment]
My idea was to have a ingame dropdown (in the f12 menu)
To select different Mtu sizes (as they are already implemented in the code, but just not configurable)

**Comment by Lacyway** [comment]
> My idea was to have a ingame dropdown (in the f12 menu) To select different Mtu sizes (as they are already implemented in the code, but just not configurable)

I realized I was not very elaborate in my response, sorry.
That sounds like a good idea, rather than a free text field.

Which part of the `NetManager` would you like this to affect?

**Comment by Lacyway** [comment]
Thanks, I will look into it when I have the time.

**Comment by ArchangelWTF** [comment]
Without making significant changes to LiteNetLib this wont be possible, then there's even the question of if we'd want to support such configurations as they would make it harder to deal with issues in the Discord. Closing for now.
