### ISSUE TITLE
[BUG] with 3.9-dev , can't start a local game when the game first time start

### ISSUE THREAD

**Issue by yhl452493373** [project-fika/Fika-Plugin#73]
I compiled the 3.9-dev branch, and i can't start a local game when the game start frist time. But after i played a coop game, the local game can be started.

I tested the SPT without our plugin, the local game can be start.

**Comment by Lacyway** [comment]
I don't understand the problem here.
What is a "local game" in this context? There is no local game nor single player functionality in Fika yet.

**Comment by yhl452493373** [comment]
start game before create or join coop game

**Comment by Lacyway** [comment]
Start what game?

**Comment by yhl452493373** [comment]
![2024-06-22 17-05  (0)](https://github.com/project-fika/Fika-Plugin/assets/26134687/9dc8defa-74a3-4504-b34e-8565b507ec8a)

**Comment by Lacyway** [comment]
This button is not supposed to be used, a patch isn't disabling it.

**Comment by yhl452493373** [comment]
> This button is not supposed to be used, a patch isn't disabling it. I'll fix it.

ok.

But if i play the coop game onece time, i can start the game by click this button.

**Comment by Lacyway** [comment]
> > This button is not supposed to be used, a patch isn't disabling it. I'll fix it.
> 
> ok.
> 
> But if i play the coop game onece time, i can start the game by click this button.
> 
> I think if i start the game by this button, the MatchingType should be Single.

I have no intention if using those buttons in the current state of Fika, nor is there any implementation of single player due to the complexity of the framework. I will add it at a later stage when we have less important things to focus on.

Bug has been fixed with [#d8a0480](https://github.com/project-fika/Fika-Plugin/commit/d8a0480b2643427a05621fbf8412a638a7b7bbd5)

**Comment by yhl452493373** [comment]
ok. thank you.
