### ISSUE TITLE
[BUG] SPT message snow command applies for everyone but the person who issued the command.

### ISSUE THREAD

**Issue by bushtail** [project-fika/Fika-Plugin#78]
**Describe the bug**

**To Reproduce**
1. Be person A.
2. Open friends list.
3. Send message "itsonlysnowalan" to SPT.
4. Play the 1-raid buffer.

**Expected behavior**
Snow to be applied on raids person A hosts, and not on raids persons B or C host.

**Screenshots**
Snow is not applied on raids hosted by person A. Snow _is_ applied on raids hosted by persons B or C.

**Log files**
Unfortunately the log files do not exist after a few alt+f4s and crashes. Server isn't mine, so I am unable to get any server logs.

**Desktop (please complete the following information):**
 - Fika Version 2.1.1, Client 0.9.8944.20016

**Additional context**
This issue was fixed upon restart. Entering the command again does not revert changes, though I remember this being the case with regular SPT as well.

**Comment by bushtail** [comment]
Thinking back this might have been a server issue.

**Comment by ArchangelWTF** [comment]
Having looked over the code in the SPT server I think I can answer this.

Due to the nature of SPT being more meant for singleplayer use "itsonlysnowalan" will trigger for everyone, so basically whoever just cleared a raid and whoever then goes next into raid will get snow.

**Comment by Lacyway** [comment]
Cannot reproduce
