### ISSUE TITLE
Loading stops at "Creating loot pools 100%"

### ISSUE THREAD

**Issue by DeenOConnor** [project-fika/Fika-Plugin#8]
I assume this is a plugin issue, because there aren't any requests to server after "Creating loot pools 100%" and base SPT still works fine after only disabling fika plugin, keeping fika server.

Reproduction steps:
1 - Install fika plugin
2 - Install fika server
3 - Start the server and the game
4 - In the game, go to any map (we tested on ground zero) and try to start a coop raid with 1 player (starting with more results in the process being stuck on waiting for players to join even if everyone already joined)
5 - Wait for the game to start and loot to load

Expected result:
Raid starts normally, allowing you to play the game

Observed result:
Loading gets permanently stuck on "Creating loot pools 100%"

Fika plugin and server built today, 28.04.2024 20:52, connected via ZeroTier, no issues with the connection itself were observed at any point.

**Comment by Lacyway** [comment]
To play Fika you have to build 3.8.1. The current code on the repo does not support 3.8.

**Comment by Lacyway** [comment]
For clarification; you can find the current working release on the discord in the releases channel.

**Comment by DeenOConnor** [comment]
Understood, thank you
