### ISSUE TITLE
[BUG] Lightkeeper door bug

### ISSUE THREAD

**Issue by Lacyway** [project-fika/Fika-Plugin#87]
When one goes inside the LK and then exit, the trader bugs out and the second door (not the keypad one but the second one) stays open and no one can talk with LK anymore as he's not there. We have to reset the raid for him to be there,

**Comment by ArchangelWTF** [comment]
This is still broke on 3.10, I suspect we'll have to sync a few things here:

- [ ] Door state leading into lightkeeper
- [ ] Ziryachy death & PMC death is supposed to lock you out of lightkeeper, does not happen.
- [ ] DSP is supposed to be decoded if killing Ziryachy or his followers or a PMC.. Not sure if this counts for the whole player group or just an individual.

**Comment by Lacyway** [comment]
A lot of the data for this is missing/guess work from patches.
We're waiting for 3.10 to start working on this.

**Comment by ArchangelWTF** [comment]
Base door state interaction is fixed with https://github.com/project-fika/Fika-Plugin/commit/71ef2ab2aded0dda14f548eb62426207b45f5584 and LK now properly interacts with other players when entering, will quickly look at the other things on the list now.

**Comment by ArchangelWTF** [comment]
Fixed in latest development branch
